# Generated by Django 6.0.1 on 2026-01-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_rename_name_player_alias_player_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='alias',
            field=models.CharField(max_length=32, unique=True, verbose_name='in game alias'),
        ),
    ]
