# Generated by Django 6.0.1 on 2026-01-31 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alias',
            field=models.CharField(default='filleralias', max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
