# Generated by Django 6.0.1 on 2026-01-24 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='player',
        ),
    ]
