# Generated by Django 6.0.1 on 2026-01-31 03:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='alias',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True, verbose_name='In game alias'),
        ),
    ]
