# Generated by Django 6.0.1 on 2026-02-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_chat_refresh',
            field=models.FloatField(default=0, verbose_name='Last chat refresh time'),
        ),
    ]
