# Generated by Django 6.0.1 on 2026-02-04 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_last_chat_refresh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_chat_refresh',
        ),
        migrations.AddField(
            model_name='user',
            name='last_update',
            field=models.FloatField(default=0, verbose_name='User last update check'),
        ),
    ]
