# Generated by Django 6.0.1 on 2026-02-08 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_user_last_chat_refresh_user_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_update',
        ),
        migrations.AddField(
            model_name='user',
            name='last_refresh',
            field=models.FloatField(default=0, verbose_name='User last successful refresh'),
        ),
    ]
