# Generated by Django 6.0.1 on 2026-01-26 02:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0003_alter_player_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=64, verbose_name='Location name')),
                ('location_type', models.CharField(choices=[('D', 'Dungeon'), ('T', 'Town')], max_length=1, verbose_name='Location type')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=32, verbose_name='region name')),
                ('biome', models.CharField(choices=[('D', 'Desert'), ('F', 'Forest'), ('P', 'Plains'), ('M', 'Mountains'), ('S', 'Swamp'), ('T', 'Tundra')], max_length=1, verbose_name='biome')),
            ],
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('size', models.IntegerField(default=10)),
                ('active', models.BooleanField(default=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.location')),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('entity_type', models.CharField(choices=[('P', 'Player'), ('N', 'NPC'), ('E', 'Enemy')], max_length=1)),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('max_health', models.IntegerField(default=1)),
                ('health', models.IntegerField(default=1)),
                ('attack_range', models.IntegerField(default=1)),
                ('attack_damage', models.IntegerField(default=1)),
                ('speed', models.IntegerField(default=1)),
                ('initiative', models.IntegerField(default=0)),
                ('max_targets', models.IntegerField(default=1)),
                ('position', models.IntegerField(db_index=True, default=None, null=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_characters', to='player.player')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_by', to='world.entity')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_entities', to='world.event')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_entities', to='world.location')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.region'),
        ),
        migrations.AddField(
            model_name='region',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.world'),
        ),
    ]
