# Generated by Django 6.0.1 on 2026-02-09 05:12

import django.db.models.deletion
import time
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('type', models.CharField(choices=[('P', 'Player'), ('E', 'Enemy')], max_length=1, verbose_name='Entity type')),
                ('attack_range', models.IntegerField(default=1)),
                ('attack_damage', models.IntegerField(default=1)),
                ('speed', models.IntegerField(default=1)),
                ('initiative', models.IntegerField(default=0)),
                ('max_targets', models.IntegerField(default=1)),
                ('max_health', models.IntegerField(default=1)),
                ('health', models.IntegerField(default=1)),
                ('level', models.IntegerField(default=1)),
                ('position', models.IntegerField(db_index=True, default=None, null=True)),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='world.entity')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=64, verbose_name='Location name')),
                ('level', models.IntegerField(default=1, verbose_name='level')),
                ('last_event', models.FloatField(blank=True, default=0, null=True)),
                ('type', models.CharField(choices=[('T', 'Town'), ('D', 'Dungeon')], max_length=1, verbose_name='Location type')),
                ('max_players', models.IntegerField(default=1)),
                ('spawn_rate', models.IntegerField(default=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=32, verbose_name='region name')),
                ('biome', models.CharField(choices=[('D', 'Desert'), ('F', 'Forest'), ('P', 'Plains'), ('M', 'Mountains'), ('S', 'Swamp'), ('T', 'Tundra')], max_length=1, verbose_name='biome')),
                ('level', models.IntegerField(default=1, verbose_name='level')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('size', models.IntegerField(default=100)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('last_update', models.FloatField(default=0)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.location')),
            ],
        ),
        migrations.CreateModel(
            name='EnemyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg', models.TextField()),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('max_health', models.IntegerField(default=1)),
                ('attack_range', models.IntegerField(default=1)),
                ('attack_damage', models.IntegerField(default=1)),
                ('speed', models.IntegerField(default=1)),
                ('initiative', models.IntegerField(default=0)),
                ('max_targets', models.IntegerField(default=1)),
                ('level', models.IntegerField(default=1)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.location')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.region'),
        ),
        migrations.CreateModel(
            name='RegionChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.FloatField(default=time.time)),
                ('message', models.TextField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.region')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='name')),
                ('start_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='world.location')),
            ],
        ),
        migrations.AddField(
            model_name='region',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.world'),
        ),
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='world.entity')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='world.event')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='world.enemytemplate')),
            ],
            bases=('world.entity',),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='world.entity')),
                ('new_status', models.BooleanField(default=False)),
                ('new_location', models.BooleanField(default=False)),
                ('active', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='world.event')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='world.location')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_characters', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('world.entity',),
        ),
    ]
