# Generated by Django 6.0.1 on 2026-01-27 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='entity',
            name='entity_type',
            field=models.CharField(choices=[('P', 'Player'), ('N', 'NPC'), ('E', 'Enemy')], db_index=True, max_length=1),
        ),
    ]
