# Generated by Django 6.0.1 on 2026-01-29 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_entity_level_alter_entity_entity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='level',
            field=models.IntegerField(default=1, verbose_name='level'),
        ),
        migrations.AddField(
            model_name='location',
            name='level',
            field=models.IntegerField(default=1, verbose_name='level'),
        ),
        migrations.AddField(
            model_name='region',
            name='level',
            field=models.IntegerField(default=1, verbose_name='level'),
        ),
        migrations.AddField(
            model_name='world',
            name='start_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='world.location'),
        ),
    ]
