# Generated by Django 6.0.1 on 2026-01-31 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0004_entity_active_entity_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='player_owner',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
