# Generated by Django 6.0.1 on 2026-01-31 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0005_remove_entity_player_owner_delete_player'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name_plural': 'entities'},
        ),
        migrations.AddField(
            model_name='location',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
