# Generated by Django 6.0.1 on 2026-01-31 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0006_alter_entity_options_location_update_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='update_time',
        ),
        migrations.AddField(
            model_name='location',
            name='last_event',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
