# Generated by Django 6.0.1 on 2026-02-03 04:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0008_regionchatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionchatmessage',
            name='sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
