# Generated by Django 6.0.1 on 2026-02-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0009_alter_regionchatmessage_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionchatmessage',
            name='sent_at',
            field=models.FloatField(default=1770092364.1253383),
        ),
    ]
