# Generated by Django 6.0.1 on 2026-02-04 03:11

import time
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0010_alter_regionchatmessage_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionchatmessage',
            name='sent_at',
            field=models.FloatField(default=time.time),
        ),
    ]
