# Generated by Django 6.0.1 on 2026-02-05 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0011_alter_regionchatmessage_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='new_status',
            field=models.BooleanField(default=False),
        ),
    ]
