# Generated by Django 6.0.1 on 2026-02-05 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0012_entity_new_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnemyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg', models.TextField()),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('max_health', models.IntegerField(default=1)),
                ('attack_range', models.IntegerField(default=1)),
                ('attack_damage', models.IntegerField(default=1)),
                ('speed', models.IntegerField(default=1)),
                ('initiative', models.IntegerField(default=0)),
                ('max_targets', models.IntegerField(default=1)),
                ('level', models.IntegerField(default=1)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.location')),
            ],
        ),
    ]
