# Generated by Django 6.0.1 on 2026-02-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0013_enemytemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='new_location',
            field=models.BooleanField(default=False),
        ),
    ]
