# Generated by Django 6.0.1 on 2026-02-06 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0014_entity_new_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='level',
        ),
        migrations.AlterField(
            model_name='entity',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='world.event'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='world.location'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='world.entity'),
        ),
        migrations.AlterField(
            model_name='event',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='last_update',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='size',
            field=models.IntegerField(default=100),
        ),
    ]
