# Generated by Django 6.0.1 on 2026-02-07 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0015_remove_event_level_alter_entity_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='world.enemytemplate'),
        ),
    ]
