# Generated by Django 6.0.1 on 2026-02-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0016_entity_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='new_status',
            field=models.BooleanField(default=True),
        ),
    ]
