# Generated by Django 6.0.1 on 2026-02-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0017_event_new_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='new_status',
        ),
        migrations.AddField(
            model_name='entity',
            name='new_event',
            field=models.BooleanField(default=False),
        ),
    ]
