# Generated by Django 6.0.1 on 2026-02-08 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0018_remove_event_new_status_entity_new_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dungeon',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='world.location')),
                ('max_players', models.IntegerField(default=4)),
                ('spawn_rate', models.IntegerField(default=5)),
            ],
            bases=('world.location',),
        ),
        migrations.RemoveField(
            model_name='entity',
            name='template',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='new_event',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='active',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='new_location',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='location',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='new_status',
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='world.location')),
                ('max_players', models.IntegerField(default=100)),
            ],
            bases=('world.location',),
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={},
        ),
        migrations.RemoveField(
            model_name='entity',
            name='entity_type',
        ),
        migrations.RemoveField(
            model_name='location',
            name='location_type',
        ),
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='world.entity')),
                ('new_event', models.BooleanField(default=False)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='world.enemytemplate')),
            ],
            bases=('world.entity',),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='world.entity')),
                ('new_status', models.BooleanField(default=False)),
                ('new_location', models.BooleanField(default=False)),
                ('new_event', models.BooleanField(default=False)),
                ('active', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='world.location')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_characters', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('world.entity',),
        ),
    ]
