# Generated by Django 6.0.1 on 2026-02-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0019_dungeon_remove_entity_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[('T', 'Town'), ('D', 'Dungeon')], default='D', max_length=1, verbose_name='Location type'),
            preserve_default=False,
        ),
    ]
