# Generated by Django 6.0.1 on 2026-02-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0020_location_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='type',
            field=models.CharField(choices=[('P', 'Player'), ('E', 'Enemy')], default='E', max_length=1, verbose_name='Entity type'),
            preserve_default=False,
        ),
    ]
