# Generated by Django 6.0.1 on 2026-02-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0021_entity_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dungeon',
            name='max_players',
        ),
        migrations.RemoveField(
            model_name='town',
            name='max_players',
        ),
        migrations.AddField(
            model_name='location',
            name='max_players',
            field=models.IntegerField(default=1),
        ),
    ]
