# Generated by Django 6.0.1 on 2026-02-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0022_remove_dungeon_max_players_remove_town_max_players_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='last_event',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
