# Generated by Django 6.0.1 on 2026-02-08 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0023_alter_location_last_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='event',
        ),
        migrations.AddField(
            model_name='enemy',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='world.event'),
        ),
        migrations.AddField(
            model_name='player',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='world.event'),
        ),
    ]
