# Generated by Django 6.0.1 on 2026-02-08 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0024_remove_entity_event_enemy_event_player_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enemy',
            name='new_event',
        ),
        migrations.RemoveField(
            model_name='player',
            name='new_event',
        ),
    ]
